# docker compose up -d --build
# version: "3.0"

services:
  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_PASS: ${DB_PASS}
    container_name: dbdb
    init: true
    env_file: .env
