# docker compose up -d --build

services:
  db:
    container_name: dbcon
    build:
      context: ./mariadb
    init: true
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network
    secrets:
      - db_root_pass
      - db_user_pass

  php:
    container_name: phpcon
    build:
      context: ./php
    init: true
    env_file: .env
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - wordpress-network
    depends_on:
      - db
    secrets:
      - wp_admin_pass
      - wp_user_pass
      - db_user_pass

  nginx:
    container_name: nginxcon
    build:
      context: ./nginx
    init: true
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - wordpress-network
    depends_on:
      - php

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_VOLUME_PATH}db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_VOLUME_PATH}wp
      o: bind

networks:
  wordpress-network:

secrets:
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  db_user_pass:
    file: ./secrets/db_user_pass.txt
  wp_admin_pass:
    file: ./secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ./secrets/wp_user_pass.txt
