# docker compose up -d --build

services:
  db:
    container_name: dbcon
    build:
      context: ./mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_PASS: ${DB_PASS}
    init: true
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network

  php:
    container_name: phpcon
    build:
      context: ./php
    init: true
    env_file: .env
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - wordpress-network
    depends_on:
      - db

  nginx:
    container_name: nginxcon
    build:
      context: ./nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        SITE_COUNTRY: ${SITE_COUNTRY}
        SITE_STATE_OR_PROVINCE: ${SITE_STATE_OR_PROVINCE}
        SITE_LOCALITY: ${SITE_LOCALITY}
        SITE_ORGANIZATION: ${SITE_ORGANIZATION}
    init: true
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - wordpress-network
    depends_on:
      - php

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_VOLUME_PATH}db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_VOLUME_PATH}wp
      o: bind

networks:
  wordpress-network:
