#! /bin/bash

echo ${DB_NAME} ${DB_USER_NAME} ${DB_PASS} ${DOMAIN_NAME} ${WP_TITLE} ${WP_ADMIN_NAME} ${WP_ADMIN_PASS} ${WP_ADMIN_EMAIL} 

echo ${WP_USER_LOGINNAME} ${WP_USER_EMAIL} ${WP_USER_ROLE} ${WP_USER_PASS} ${WP_USER_DISPLAYNAME}

mysqld_safe
